### PR TITLE
Fix various typos.

### PR DESCRIPTION
**Pull request by csukuangfj**

### CODE REVIEW

**Comment by awni** [comment]
Fangjun, thank you for the input! I have pulled in your changes and put them in a separate commit. (I kept figure lower case as that's the style I prefer, but otherwise accepted all of your changes).

I hope it is ok that I [acknowledge](https://github.com/awni/automata_ml/blob/main/latex/acknowledge.tex) you for the feedback.

Refer to commit e38946aa53141246946081530472c14987a4b0e4.

**Comment by awni** [comment]
PS, I was thinking about having an alternate version of the notebooks which supported K2 (so we could have both K2 and GTN). Something like they did in the [d2l book](https://d2l.ai/chapter_deep-learning-computation/model-construction.html#the-sequential-block) for different frameworks. Let me know if this is something you would be interested in contributing to.

**Comment by csukuangfj** [comment]
> I kept figure lower case as that's the style I prefer

In that case, it would be great if you use it consistently in your document.

**Comment by csukuangfj** [comment]
> I hope it is ok that I acknowledge you for the feedback.

thanks!

**Comment by csukuangfj** [comment]
> PS, I was thinking about having an alternate version of the notebooks which supported k2 (so we could have both k2 and GTN). Something like they did in the [d2l book](https://d2l.ai/chapter_deep-learning-computation/model-construction.html#the-sequential-block) for different frameworks. Let me know if this is something you would be interested in contributing to.

Yes, it is a good idea and we are glad to do that.

cc @danpovey @glynpu @liliana404 @pkufool

**Comment by awni** [comment]
@csukuangfj 

> In that case, it would be great if you use it consistently in your document.

I didn't see any inconsistency here, did you?

**Comment by csukuangfj** [comment]
> I didn't see any inconsistency here, did you?


Let me show you one place:
https://github.com/awni/automata_ml/blob/e38946aa53141246946081530472c14987a4b0e4/latex/acceptors_and_transducers.tex#L13

**Comment by awni** [comment]
Yes it should be capitalized at the beginning of the sentence. That is an exception to the rule.

**Comment by csukuangfj** [comment]
> Yes it should be capitalized at the beginning of the sentence. That is an exception to the rule.

Aha, I see. Thanks

**Pull request closed without merging**
